pipeline {
    agent any
    stages {
        stage('Example') {
            steps { 
                echo 'Hello World'
            }
        }
        stage('Example2') {
            steps { 
                echo 'Hello World again'
            }
        }
    }
}
